version: "3.8"
services:
  php:
    image: ghcr.io/rilgilang//larapeler-simpan-pinjam-musi
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - proxy

networks:
  proxy:
    driver: bridge