version: "3.8"
services:
  php:
    image: ghcr.io/rilgilang/larapeler-simpan-pinjam-musi
    volumes:
      - .:/var/www/html
    ports:
      - "6969:6969"
    networks:
      - proxy

networks:
  proxy:
    driver: bridge